global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Graphics;
global using System;
global using System.Collections.Generic;
global using Terraria;
global using Terraria.ID;
global using Terraria.ModLoader;
global using TigerUtilsLib;
global using static TigerUtilsLib.TigerClasses;
global using static TigerUtilsLib.TigerUtils;
